#include <bits/stdc++.h>
using namespace std;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int n;
    long long m;
    cin >> n >> m;
    vector<long long> a(n);
    for (int i = 0; i < n; ++i) {
        cin >> a[i];
    }

    sort(a.begin(), a.end());

    long long total_download = accumulate(a.begin(), a.end(), 0LL);
    long long total_watch = n; // 1 minute per video

    // We need to find the minimum time T such that we can schedule all downloads and watches.
    // The key insight: we can watch at most 1 video at a time, and we can download at most 1 video at a time.
    // The total time is at least total_download + total_watch, but we can overlap watching with downloading.
    // The only constraint is that we cannot start downloading a video if there is not enough free space.
    // We can delete a video immediately after watching it (which takes 1 minute).
    // So the hard disk space constraint is the main bottleneck.

    // Let's think about the order: we should download videos in some order, and watch them in the same order.
    // While downloading a video, we can watch a previously downloaded one.
    // The total time is the sum of download times plus the time we are forced to wait because of disk space.
    // Actually, we can think of it as: we have a buffer of size m. We can fill it with downloads, and we can empty it by watching.
    // The process: at time 0, we start downloading the first video. It takes a[0] time. During that time, we cannot watch anything (no video ready).
    // After a[0] time, we can start watching video 0 (takes 1 minute) and simultaneously start downloading video 1.
    // While watching video 0, we download video 1. After 1 minute, video 0 finishes watching, we delete it, freeing a[0] space.
    // Then we can start watching video 1 (if it has finished downloading) or wait.
    // The constraint: when we start downloading video i, the sum of sizes of videos currently on disk (those downloaded but not yet watched) plus a[i] must be <= m.
    // Since we watch in the same order as download, the videos on disk are exactly the ones we have downloaded but not yet finished watching.
    // At the moment we start downloading video i, we have finished watching videos 0..i-1, so they are deleted. So the only videos on disk are those we are currently downloading (if any) and possibly the one we are currently watching? Wait, we can't download and watch the same video simultaneously. We watch a video only after it's fully downloaded. So when we start downloading video i, we might be in the middle of watching video i-1 (if it finished downloading before we started downloading video i). But video i-1 is still on disk until we finish watching it. So the space used is: size of video currently being watched (if any) + size of video currently being downloaded (if any, but we are about to start downloading video i, so the current download is not yet started). Actually, we start downloading video i exactly when we finish downloading video i-1? Not necessarily: we could have idle time between downloads if we are waiting for space. But we can start downloading video i as soon as we have enough free space. The free space at any time is m - (sum of sizes of videos currently on disk). Videos on disk are those that have been fully downloaded but not yet completely watched. Since we watch videos sequentially, at any time there is at most one video being watched (the one that finished downloading most recently and hasn't finished its 1-minute watch). Also, there might be a video currently being downloaded. But we cannot start a new download while another is in progress. So at the moment we decide to start downloading video i, the previous download (video i-1) must have finished. At that moment, we might still be watching video i-1 (if we started watching it immediately after its download finished, and 1 minute hasn't passed yet). So the disk contains video i-1 (being watched) and possibly some other videos? No, because we watch videos in order and delete them immediately after watching. So at the start of download i, the only video on disk is video i-1 if we are still watching it. But wait: what if the download of video i-1 finished, we started watching it, and during that 1 minute we could not start downloading video i because of space? Then we wait. During that wait, video i-1 is still on disk. So the space used is a[i-1]. We can start downloading video i only if a[i] <= m - a[i-1] (if we are still watching video i-1) or a[i] <= m (if we have already finished watching video i-1 and deleted it). But since we can delete video i-1 only after 1 minute of watching, the earliest we can start downloading video i without waiting is if a[i] <= m - a[i-1] and we start immediately after video i-1 finishes downloading. If a[i] > m - a[i-1], we must wait until video i-1 finishes watching and is deleted, which takes 1 minute from the start of watching. But we could also delay the start of watching video i-1? No, we want to minimize total time, so we should start watching as soon as possible.

    // This suggests a greedy strategy: process videos in some order. The total time will be the sum of download times plus the sum of "forced idle" times where we cannot download because of space.
    // Let's simulate with a priority queue or something? But n is up to 2e5, m up to 1e9. We need O(n log n) or O(n).

    // Alternative perspective: The total time is the time when the last video finishes watching. We can think of the schedule as a sequence of actions: download video i (takes a[i] time), watch video i (takes 1 time). Downloads must be sequential, watches must be sequential. The only overlap is that we can watch a video while downloading the next one. The constraint: at any time, the total size of videos that have been downloaded but not yet watched cannot exceed m. Since we watch in the same order as download, the set of downloaded-but-not-watched videos is always a contiguous suffix of the downloaded videos? Actually, if we download in order 0,1,2,... and watch in the same order, then at any time, the videos that are downloaded but not watched are exactly the ones from the currently watching index to the currently downloading index. But since we can only watch one at a time, the watching index is always <= downloading index. The difference is the number of videos fully downloaded but not yet watched. Their total size must be <= m. But note that the video currently being downloaded is not yet on disk (it's being downloaded, space is reserved at start). So the space used is the sum of sizes of videos that have finished downloading but not yet finished watching. That includes the video currently being watched (if any) and any videos that finished downloading but haven't started watching yet (if we downloaded ahead). Can we download ahead? Yes, we can download video i+1 while watching video i, and if a[i+1] is small, it might finish before we finish watching video i. Then we have video i+1 fully downloaded, but we can't watch it until we finish video i. So it sits on disk. Then we could even start downloading video i+2 if space permits, while still watching video i. So we can have multiple fully downloaded videos waiting to be watched. The space constraint is that the sum of sizes of all fully downloaded but unwatched videos (including the one currently being watched) must be <= m at all times.

    // This is similar to a buffer of size m. We produce videos (download) and consume them (watch). Production of video i takes a[i] time, consumption takes 1 time. Production and consumption can happen simultaneously, but production is sequential, consumption is sequential. The buffer holds produced but not consumed videos. The total size in buffer <= m. We want to minimize makespan.

    // This is a known problem: scheduling with limited buffer. The optimal strategy is to process videos in order of increasing size? Or maybe we should always keep the buffer as full as possible to avoid idle time? Actually, we want to avoid idle time on the consumer (watching) because watching is fast (1 minute) and we have to watch all n videos, so total watch time is n. The total download time is sum a[i]. The only way total time exceeds sum a[i] + n is if the consumer is idle waiting for a video to download because the buffer is empty. But the buffer can be empty only if we are forced to wait for space to download. Wait, if the buffer is empty, that means we have no videos ready to watch. That happens if we haven't downloaded the next video yet. But we can always be downloading something as long as there are videos left and space permits. The only reason we wouldn't be downloading is if we are waiting for space. So idle time on the downloader is the problem. The consumer (watching) is never idle if we always have a video ready. But if we have to wait for space, we might not be able to download, so the buffer might become empty later, causing consumer to wait. So the total time is sum a[i] + n + (total time downloader is idle). We want to minimize downloader idle time.

    // When does downloader idle? When the next video we want to download has size > free space. Free space = m - (sum of sizes of videos currently in buffer). The buffer contains videos that are downloaded but not yet watched. Since we watch at rate 1 video per minute, the buffer occupancy decreases by the size of the video we finish watching every 1 minute. So if we have a large video that doesn't fit, we must wait until enough videos are watched and removed to free up space.

    // This suggests we should order the videos to minimize the waiting. Intuitively, we should download small videos first to quickly free up space? Or large videos first? Let's think: if we download a large video, it occupies space for a long time (until it is watched). But watching it takes only 1 minute, but we can only watch it after it's downloaded. If we download it early, it might block space for other videos. If we download it late, we might have to wait for space. Actually, the waiting happens when we want to download a video but the sum of sizes of already downloaded but unwatched videos plus this video exceeds m. The already downloaded but unwatched videos are those that we downloaded but haven't gotten around to watching yet. Since we watch in order, if we download a large video early, it will sit in the buffer until we watch all videos before it. That could take a while if there are many videos before it. So it's better to download large videos later, so they don't occupy space while we are processing smaller ones. Conversely, small videos can be downloaded quickly and watched quickly, freeing space. So we should sort videos by size? But wait, we can also interleave downloads and watches. The order of watching is the same as the order of downloading? Not necessarily! The problem says: "The order of watching does not matter, since Monocarp needs to watch all of them anyway." So we can choose any order to watch the videos. We can download in one order and watch in a different order? The problem says: "Once a video is fully downloaded to the hard disk, Monocarp can watch it. ... When Monocarp finishes watching a video, he doesn't need it on the hard disk anymore, so he can delete the video...". It does not say he must watch them in the order they were downloaded. He can watch any downloaded video at any time. So we can download videos in some order, and watch them in any order. This is crucial! The hints say: "Think about how the order of watching videos affects the total time." and "How should Monocarp choose which videos to watch first?" So we can reorder both downloading and watching independently? But downloading is sequential, watching is sequential. We can decide which video to download next, and which downloaded video to watch next. This is a classic scheduling problem with buffer.

    // Let's re-read: "A video should be downloaded before it can be watched. ... Once a video is fully downloaded to the hard disk, Monocarp can watch it. ... When Monocarp finishes watching a video, he doesn't need it on the hard disk anymore, so he can delete the video...". There is no constraint that videos must be watched in download order. So we can download videos in any order, and watch them in any order. The only constraint is that a video must be fully downloaded before it can be watched. And we can delete it immediately after watching. So we have a pool of videos. We can choose to download any video at any time (if space permits), and we can choose to watch any already downloaded video at any time. We want to minimize the completion time of the last watch.

    // This is equivalent to: we have n jobs, each with processing time a[i] on machine 1 (download) and processing time 1 on machine 2 (watch). Machine 1 and machine 2 can work in parallel. There is a buffer of capacity m between them. Jobs must go through machine 1 then machine 2. Machine 1 can only process one job at a time, machine 2 can only process one job at a time. The buffer holds jobs that have finished on machine 1 but not yet started on machine 2. The total size of jobs in the buffer cannot exceed m. We want to minimize makespan.

    // This is a two-machine flow shop with limited intermediate storage. The optimal schedule for such problems is often to sort jobs by some criterion. Since machine 2 has unit processing time for all jobs, it's a special case.

    // Let's think: we want to keep machine 2 busy as much as possible, because it's the bottleneck? Actually, machine 2 takes 1 minute per job, total n minutes. Machine 1 takes sum a[i] minutes. If sum a[i] <= n, then machine 1 is not the bottleneck, and we can easily finish in n + something? But we also have buffer constraints. The total time is at least max(sum a[i] + 1, n + something)? Wait, the last job must be downloaded then watched. So total time >= max( sum a[i] + 1, n + something )? Actually, the makespan is the time when the last job finishes on machine 2. Machine 2 must process n jobs sequentially, so it takes at least n time units. Machine 1 must process all jobs, taking sum a[i] time. They can overlap. The makespan is at least max( sum a[i] + 1, n )? Not exactly: the last job on machine 2 must have finished machine 1 before it can start machine 2. So if machine 1 finishes the last job at time T1, then machine 2 finishes at T1 + 1 (if machine 2 is idle before that) or later if machine 2 is busy. So makespan >= max( sum a[i] + 1, n + idle_time_on_machine2 ). But machine 2 idle time occurs if it runs out of jobs in the buffer. That happens if machine 1 is slow or blocked.

    // The buffer constraint: at any time, the sum of sizes of jobs in the buffer (completed on M1, not yet started on M2) must be <= m. This can cause machine 1 to block if the next job it wants to process is too large to fit in the remaining buffer space. In that case, machine 1 must wait until machine 2 removes some jobs from the buffer.

    // We can choose the order of jobs on both machines. Since machine 2 processing times are all 1, the order on machine 2 doesn't affect the total time as long as we always have a job to process? Actually, it does affect when we free up space. If we watch a large job, we free up a lot of space. If we watch a small job, we free up little space. To unblock machine 1 quickly, we should watch large jobs first to free up space. But we can only watch jobs that have been downloaded. So we might want to download large jobs early so they are available to be watched when we need to free space? Or download them late so they don't clog the buffer? This is tricky.

    // Let's consider the hints:
    // Hint 1: Think about how the order of watching videos affects the total time.
    // Hint 2: Try to minimize the time spent waiting for free space.
    // Hint 3: What is the maximum number of videos Monocarp can watch at the same time? (Answer: 1, because watching is sequential)
    // Hint 4: How should Monocarp choose which videos to watch first?
    // Hint 5: Does it make sense to download videos that don't fit into the hard disk? (But all a_i <= m, so any single video fits. The question might mean: does it make sense to download a video if it doesn't fit along with the currently stored videos? We have to wait until space is freed.)
    // Hint 6: Consider videos with equal sizes.

    // Let's try to find a strategy. Suppose we decide the order of watching. Since watching takes 1 minute each, the watching schedule is just a permutation. At time t=0, we start downloading some video. We can also start watching only after at least one video is downloaded. The total time will be the sum of download times plus any idle time on the downloader. The downloader idle time occurs when we want to download a video but the buffer is full (i.e., the sum of sizes of downloaded but unwatched videos = m, and the next video we want to download has size > 0, but we can't start because it would exceed m). Actually, if the buffer is exactly full, we cannot start any new download until a video is watched and removed. So we must wait.

    // To minimize idle time, we should avoid filling the buffer with videos that take a long time to watch? But all videos take exactly 1 minute to watch. So the rate of freeing space is determined by the sizes of the videos we watch. If we watch a video of size s, we free s megabytes after 1 minute. So to free space quickly, we should watch the largest possible videos first. That suggests we should prioritize watching large videos. But we can only watch videos that are already downloaded. So we should download large videos early so they are ready to be watched when we need to free space. However, downloading a large video takes a long time, during which we might be watching other videos and freeing space. If we download a large video first, it occupies space for a long time (during its download, it's not in the buffer yet; space is reserved at start of download, so during download, it occupies space). Actually, when we start downloading a video of size s, we immediately reserve s megabytes. So during the download, that space is used. So a large video ties up space for its entire download duration. If we download it first, we have no other videos to watch, so we can't free space. We just wait for it to download, then watch it (1 minute), then we can free its space. That might be inefficient if we could instead download a small video first, watch it quickly, and then use the freed space to download larger ones? But the small video frees little space. 

    // Let's simulate small examples to gain intuition.

    // Example 1: n=5, m=6, a=[1,2,3,4,5]. Output 16.
    // Example 2: n=5, m=5, a=[1,2,3,4,5]. Output 17.
    // Example 3: n=4, m=3, a=[1,3,2,3]. Output 12.

    // Let's try to find a schedule for Example 1 manually.
    // m=6. Videos: 1,2,3,4,5.
    // One possible schedule: Download 1 (takes 1, time 0-1). At time 1, 1 is downloaded. Start watching 1 (time 1-2) and simultaneously start downloading 2 (size 2, time 1-3). At time 2, 1 finishes watching, delete it (free 1). Now disk has 2 (still downloading until time 3). At time 2, we can start downloading 3? Space used: 2 is downloading (size 2), so free space = 6-2=4. 3 has size 3, so we can start downloading 3 at time 2. Download 3 from time 2 to 5. At time 3, download of 2 finishes. Disk now has 2 (fully downloaded, waiting to be watched) and 3 (downloading). We are watching? We finished watching 1 at time 2. We can start watching 2 at time 3? Actually, we could start watching 2 as soon as it finishes downloading at time 3. So at time 3, start watching 2 (time 3-4) and continue downloading 3. At time 4, finish watching 2, delete it (free 2). Disk now has 3 (still downloading until time 5). Free space = 6-3=3. We can start downloading 4 (size 4)? 4 > 3, so cannot. We must wait. At time 5, download of 3 finishes. Disk has 3 (fully downloaded). We are not watching anything (finished watching 2 at time 4). So we can start watching 3 at time 5 (time 5-6). Also, we can start downloading 4? At time 5, disk has 3 (being watched). Free space = 6-3=3. 4 needs 4, so cannot. We must wait until 3 is deleted. At time 6, finish watching 3, delete it (free 3). Disk empty. Start downloading 4 (size 4) at time 6, takes until 10. At time 10, start watching 4 (10-11) and download 5 (size 5)? At time 10, disk has 4 (being watched). Free space = 6-4=2. 5 needs 5, cannot. Wait until 4 finishes watching at 11, delete 4. Start downloading 5 at 11, takes until 16. Watch 5 at 16-17. Total time 17. But output is 16. So my schedule is suboptimal.

    // Let's try a different order. Maybe download smaller videos first? Or larger first? Let's try downloading in order: 5,4,3,2,1? 
    // Start download 5 (0-5). At 5, watch 5 (5-6) and download 4? Space: 5 is watching, free=1. 4 needs 4, cannot. Wait until 6, delete 5. Download 4 (6-10). At 10, watch 4 (10-11) and download 3? Free space: 4 watching, free=2. 3 needs 3, cannot. Wait until 11, delete 4. Download 3 (11-14). At 14, watch 3 (14-15) and download 2? Free: 3 watching, free=3. 2 needs 2, ok. Download 2 (14-16). At 15, finish watching 3, delete 3. Disk has 2 (downloading until 16). At 15, we can start watching? No video ready except maybe we could have downloaded something else? At 16, download 2 finishes. Watch 2 (16-17) and download 1? Free: 2 watching, free=4. 1 fits. Download 1 (16-17). At 17, finish watching 2, delete 2. Watch 1 (17-18). Total 18. Worse.

    // What if we interleave? The optimal might be to download in order of increasing size? Let's try: 1,2,3,4,5 gave 17. What about 1,3,2,4,5? 
    // Download 1 (0-1). Watch 1 (1-2), download 3 (1-4). At 2, delete 1. Disk: 3 downloading. Free=3. Can we download 2? 2 fits. Download 2 (2-4). At 4, both 3 and 2 finish downloading. Disk has 3 and 2. We can watch one. Which to watch first? If we watch 3 (4-5), disk has 3 (watching) and 2 (waiting). Free = 6-3-2=1. Can't download 4 (needs 4). At 5, delete 3. Disk has 2. Watch 2 (5-6). Free=6-2=4. Can we download 4? 4 fits. Download 4 (5-9). At 6, delete 2. Disk: 4 downloading. Free=2. Can't download 5. At 9, download 4 finishes. Watch 4 (9-10). Free=6-4=2. Can't download 5. At 10, delete 4. Download 5 (10-15). Watch 5 (15-16). Total 16! That matches output. So the order of downloading was 1,3,2,4,5 and watching order was 1,3,2,4,5 (same as download order? Actually we watched 1, then 3, then 2, then 4, then 5. So we watched in the order they finished downloading? 1 finished first, then 3 and 2 finished at the same time, we chose to watch 3 then 2. That was crucial: we watched the larger one first to free more space sooner. So the watching order matters: we should always watch the largest available video first to free up space quickly. This is a key insight!

    // Let's test this greedy strategy: always watch the largest downloaded video first. And for downloading, what order? In the above, we downloaded 1, then 3, then 2, then 4, then 5. Why 3 before 2? Because after 1, we had free space 5, we could download 3 (size 3) or 2 (size 2). We chose 3. Why? Maybe we want to download larger videos earlier so they are available to be watched when we need to free space? But we also need to consider that downloading a large video ties up space for a long time. In this case, downloading 3 first allowed us to also download 2 concurrently? No, downloads are sequential. We downloaded 3 from 1 to 4, and 2 from 2 to 4. Wait, we started downloading 2 at time 2, while 3 was still downloading. That's not allowed! The problem says: "It is not allowed to run two or more downloads in parallel." So we cannot download 2 while 3 is downloading. My schedule above had overlapping downloads, which is invalid. Let's re-read: "Once the download is started, it cannot be interrupted. It is not allowed to run two or more downloads in parallel." So only one download at a time. In my schedule, I had download 3 from 1 to 4, and download 2 from 2 to 4. That's parallel. Invalid.

    // So we must download sequentially. Let's correct: 
    // Valid schedule: Download 1 (0-1). Watch 1 (1-2). At 1, start download 3 (1-4). At 2, delete 1. At 4, download 3 finishes. Watch 3 (4-5). At 4, start download 2 (4-6). At 5, delete 3. At 6, download 2 finishes. Watch 2 (6-7). At 6, start download 4 (6-10). At 7, delete 2. At 10, download 4 finishes. Watch 4 (10-11). At 10, start download 5? Free space at 10: disk has 4 (watching). Free = 6-4=2. 5 needs 5, cannot. So wait until 11, delete 4. Start download 5 (11-16). Watch 5 (16-17). Total 17. Still 17.

    // But the output is 16. So there must be a better schedule without parallel downloads. Let's find one that gives 16.
    // Maybe we can watch videos in a different order than download order. We can download a video, then not watch it immediately, but download another video while the first sits in the buffer. Then we can watch the largest one when needed.

    // Let's try: Download 1 (0-1). At 1, we have 1 downloaded. Instead of watching it immediately, we could start downloading 2? But we can watch and download simultaneously. So at 1, we can start watching 1 AND start downloading 2. That's allowed. So at 1, start watching 1 (1-2) and start downloading 2 (1-3). At 2, 1 finishes, delete it. Disk has 2 (downloading until 3). At 3, 2 finishes. Now we have 2 ready. We can watch 2 (3-4) and start downloading 3 (3-6). At 4, delete 2. Disk has 3 downloading. At 6, 3 finishes. Watch 3 (6-7) and start downloading 4 (6-10). At 7, delete 3. Disk has 4 downloading. At 10, 4 finishes. Watch 4 (10-11) and start downloading 5? At 10, disk has 4 (watching), free=2. 5 doesn't fit. Wait until 11, delete 4. Download 5 (11-16). Watch 5 (16-17). Total 17.

    // What if we don't watch 1 immediately? At time 1, we have 1 downloaded. We could start downloading 2 without watching 1. But we can do both. Watching 1 doesn't prevent downloading 2. So watching immediately is always better because it frees space sooner. So we should always watch if there is a downloaded video and we are not currently watching. The only reason to delay watching is if we want to watch a different video first. But we can only watch one at a time. So if we have multiple downloaded videos, we can choose which to watch. In the above, at time 3, we had only 2. At time 6, only 3. So no choice.

    // To get 16, we need to somehow have a larger video ready earlier to free more space. How can we get a large video ready early? We must download it early. But downloading a large video takes time. If we download 5 first: 0-5. At 5, watch 5 (5-6). At 5, start download 4? Free space: 5 watching, free=1. 4 doesn't fit. Wait until 6, delete 5. Download 4 (6-10). Watch 4 (10-11). Download 3 (11-14). Watch 3 (14-15). Download 2 (15-17). Watch 2 (17-18). Download 1 (18-19). Watch 1 (19-20). Total 20. Worse.

    // What if we download 4 first? 0-4. Watch 4 (4-5). At 4, start download 5? Free: 4 watching, free=2. 5 doesn't fit. Wait until 5, delete 4. Download 5 (5-10). Watch 5 (10-11). Download 3 (11-14). Watch 3 (14-15). Download 2 (15-17). Watch 2 (17-18). Download 1 (18-19). Watch 1 (19-20). Total 20.

    // What if we download 3 first? 0-3. Watch 3 (3-4). At 3, start download 4? Free: 3 watching, free=3. 4 doesn't fit. Wait until 4, delete 3. Download 4 (4-8). Watch 4 (8-9). Download 5? Free: 4 watching, free=2. 5 doesn't fit. Wait until 9, delete 4. Download 5 (9-14). Watch 5 (14-15). Download 2 (15-17). Watch 2 (17-18). Download 1 (18-19). Watch 1 (19-20). Total 20.

    // What if we download 2 first? 0-2. Watch 2 (2-3). At 2, start download 3? Free: 2 watching, free=4. 3 fits. Download 3 (2-5). At 3, delete 2. Disk: 3 downloading. At 5, 3 finishes. Watch 3 (5-6). At 5, start download 4? Free: 3 watching, free=3. 4 doesn't fit. Wait until 6, delete 3. Download 4 (6-10). Watch 4 (10-11). Download 5? Free: 4 watching, free=2. Wait until 11, delete 4. Download 5 (11-16). Watch 5 (16-17). Download 1? We haven't downloaded 1 yet. We can download 1 at any time. Actually, we missed 1. Let's insert 1 somewhere. Total so far: 2,3,4,5. We need to download 1. We can download 1 when there is space. For example, after downloading 2, we could download 1 instead of 3? Let's try: 0-2 download 2. Watch 2 (2-3). At 2, start download 1 (2-3). At 3, delete 2, 1 finishes. Watch 1 (3-4). At 3, start download 3 (3-6). At 4, delete 1. Disk: 3 downloading. At 6, 3 finishes. Watch 3 (6-7). Start download 4 (6-10). At 7, delete 3. At 10, 4 finishes. Watch 4 (10-11). Start download 5? Free: 4 watching, free=2. Wait until 11, delete 4. Download 5 (11-16). Watch 5 (16-17). Total 17.

    // Still 17. How to get 16? Let's look at the sample output 16. Maybe we can download videos in order: 1, 2, 4, 3, 5? Or something else.

    // Let's try to think of the buffer as a priority queue of downloaded videos. We always watch the largest available video. For downloading, we should choose the next video to download such that we minimize idle time. This is similar to the problem of scheduling with limited buffer where we want to keep the downloader busy. The downloader can be busy if there is a video that fits in the remaining space. If no video fits, we must wait until we watch something and free space. To avoid waiting, we should try to have a video that fits. That means we should not fill the buffer with videos that are too large, leaving no room for the next download. So we should download smaller videos first? But we also want large videos to be available for watching to free space quickly. There's a trade-off.

    // Let's consider the total time formula. The total time is the sum of download times plus the sum of idle times on the downloader. The idle times occur when the buffer is full (or rather, when the next video we want to download doesn't fit in the free space). The free space is m - sum of sizes of videos currently in the buffer. The buffer contains videos that are downloaded but not yet watched. Since we watch one video per minute, the buffer size decreases by the size of the watched video every minute. So if we are blocked, we wait until enough videos are watched to free up the required space. The waiting time depends on which videos we choose to watch. To minimize waiting, we should watch the largest videos first, because they free the most space per minute of watching. That is a solid greedy choice: always watch the largest downloaded video. This is optimal because watching any video takes 1 minute, and we want to maximize the space freed per minute. So the watching strategy is fixed: maintain a max-heap of downloaded videos, and always watch the largest.

    // Now, what about the download order? We have a set of videos. We can choose which one to download next. At any time, we can start downloading a video if its size <= free space. The free space is m - sum of sizes of videos currently in the buffer (including the one being watched? Actually, the one being watched is in the buffer until it finishes watching. So yes, it occupies space). Also, if we are currently
